version: 2
registries:
  npm-registry-npm-pkg-github-com-platformbuilders:
    type: npm-registry
    url: https://npm.pkg.github.com/platformbuilders
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_PLATFORMBUILDERS_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Brazil/East
  open-pull-requests-limit: 10
  reviewers:
  - digitals
  labels:
  - dependencies
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
    - 17.0.3
  - dependency-name: eslint-plugin-flowtype
    versions:
    - 5.2.2
    - 5.3.1
    - 5.4.0
    - 5.6.0
    - 5.7.1
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: pinst
    versions:
    - 2.1.6
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: "@types/react-native"
    versions:
    - 0.63.49
    - 0.63.50
    - 0.63.51
    - 0.64.0
    - 0.64.2
  - dependency-name: eslint-plugin-sonarjs
    versions:
    - 0.6.0
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.0.3
  - dependency-name: eslint-plugin-import
    versions:
    - 2.22.1
  - dependency-name: ini
    versions:
    - 1.3.8
  registries:
  - npm-registry-npm-pkg-github-com-platformbuilders
